name: deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking-out latest source
        uses: actions/checkout@v4
      - name: Setting up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enabling corepack
        run: corepack enable
      - name: Installing node modules
        run: yarn install --immutable
      - name: Checking types
        run: yarn typecheck
      - name: Linting
        run: yarn lint
      - name: Checking formatting
        run: yarn prettier --check src tests
      - name: Running tests
        run: yarn test
      - name: Building server & client
        run: yarn build
        env:
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
      - name: Copy package.json
        run: cp package.json dist/package.json
      - name: Uploading files to server
        if: github.event_name == 'push'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
      - name: Install node modules, build & restart apps via cloudlinux
        if: github.event_name == 'push'
        uses: fifsky/ssh-action@5a841de87115730aff750ac127773e3b2b3f56dd
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            export DEPLOY_PATH=/home/${{ secrets.SSH_USERNAME }}/${{ secrets.DEPLOY_DIRECTORY }}
            cloudlinux-selector install-modules --json --interpreter nodejs --user $USER --app-root $DEPLOY_PATH
            cloudlinux-selector restart --json --interpreter nodejs --user $USER --app-root $DEPLOY_PATH
