name: deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking-out latest source
        uses: actions/checkout@v4
      - name: Setting up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enabling corepack
        run: corepack enable
      - name: Installing node modules
        run: yarn install --immutable
      - name: Checking types
        run: yarn typecheck
      - name: Linting
        run: yarn lint
      - name: Checking formatting
        run: yarn prettier --check .
      - name: Running tests
        run: yarn test
      - name: Building server & client
        run: yarn build
        env:
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
      - name: Copy package.json
        run: cp apps/web/package.json apps/web/dist/package.json
      - name: Force restart post upload
        run: mkdir -p apps/web/dist/tmp && echo $EPOCHSECONDS > apps/web/dist/tmp/restart.txt
      - name: Uploading files to server
        if: github.event_name == 'push'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./apps/web/dist/
